name: finora
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.0+5

environment:
  sdk: '3.9.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
#  hive_ce:
#  hive_ce_flutter:
  path_provider: ^2.1.5
  intl: ^0.20.2
  google_fonts: ^6.3.1
  animations: ^2.0.11
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  sqlite3_flutter_libs: ^0.5.39
  flutter_animate:

  # Routing
  go_router: ^13.2.0

  # Firebase (for optional backup)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^6.3.0
  cloud_firestore:
  # Utilities
  file_picker: ^10.3.2
  share_plus: ^11.1.0
  flutter_slidable: ^4.0.1
  shared_preferences: ^2.5.3
  math_expressions:
  icons_plus: ^5.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.28.0
  build_runner: ^2.5.4
  riverpod_generator: ^2.6.5
#  hive_ce_generator:

flutter:
  uses-material-design: true
